[package]
name = "Drone"
version = "0.1.0"
edition = "2024" 

[dependencies]
Common = { path = "../Common" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
heapless = "0.7"
nb = "1.0"
teensy4-bsp = "0.5"
postcard = "1.0"

